language: python

python:
  - "3.7"
  - "3.6"
  - "3.5"
  - "3.4"

service:
  - mariadb

before_install:
  - export APP_SETTINGS="project.server.config.TestingConfig"
  - export SECRET_KEY="justatest"

install:
  - pipenv install

before_script:
  - psql -c "CREATE USER lodgekeeper WITH ENCRYPTED PASSWORD 'Test3r$';" -U postgres
  - psql -c "CREATE DATABASE lodgekeeper;" -U postgres
  - psql -c "CREATE DATABASE lodgekeeper_test;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE lodgekeeper TO lodgekeeper;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE lodgekeeper_test TO lodgekeeper;" -U postgres
  - python manage.py db init
  - python manage.py db migrate
  - python manage.py db upgrade

script:
  - python manage.py cov

after_success:
  coveralls
